let mdate=new Date()
console.log(mdate)
console.log(mdate.toString())
console.log(typeof(mdate))
let createdate=new Date(2026,1,14)
console.log(createdate.toDateString())
let times=Date.now()
console.log(times) 
console.log(createdate.getTime())